# Generated by Django 5.1 on 2024-09-14 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('lore', models.TextField()),
                ('champ_img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive_img', models.ImageField(upload_to='media/')),
                ('q_img', models.ImageField(upload_to='media/')),
                ('w_img', models.ImageField(upload_to='media/')),
                ('e_img', models.ImageField(upload_to='media/')),
                ('r_img', models.ImageField(upload_to='media/')),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apileague.champions')),
            ],
        ),
    ]
