# Generated by Django 5.1 on 2024-09-14 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apileague', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Champions',
            new_name='Champion',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
